name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Formatting
        run: black web_app/
      - name: Linting
        run: pylint --rcfile=web_app/.pylintrc -j=0 web_app/
      - name: Type checking
        run: mypy --config-file=web_app/mypy.ini web_app/
      - name: Unit tests
        run: pytest -c web_app/pytest.ini
